# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chat

  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  target 'chat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'lottie-ios', :path => '../node_modules/lottie-ios'

    pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  end

  target 'chatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'chat-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chat-tvOS


end
